version: "3.7"

services:
  express:
    build: .
    container_name: express
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  mysql:
    image: mysql:5.7
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lecture
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    platform: linux/x86_64
