version: "3.7"
platform: linux/x86_64
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: lecture_database

    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lecture
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
